language: go

sudo: false

os:
  - linux

services:

go:
  - 1.6.3
  - 1.7.1
  - tip

matrix:
  allow_failures:
    - go: tip

branches:
  only:
  - master

env:
  global:
    - GOARCH=amd64

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - go env && pwd

install:
 - go get -t ./...
 - go get -u github.com/stretchr/testify/assert
 - go get -u github.com/golang/lint/golint
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u golang.org/x/tools/cmd/cover
 - go get -u github.com/mattn/goveralls
 - go get -u github.com/erikstmartin/go-testdb

before_script:
# wait mongodb
  - sleep 15

script:
 - go vet ./...
 - diff <(goimports -d .) <(printf "")
 - diff <(golint ./...) <(printf "")
# - go test -v -cpu=2 -short ./...
# - go test -v -cpu=1,2,4 -short ./...
 - go test -v -covermode=count -coverprofile=coverage.out
 - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
 - GOOS=linux && go build ./...
 - GOOS=windows && go build ./...


after_success:
  - go env && pwd

after_failure:
  - go env && pwd

before_deploy:

deploy:

after_deploy:

after_script:
